<?xml version="1.0" encoding="UTF-8"?>
<!--Created with WSDLGenerator 2.0.0 by Amadeus SAS-->
<!--  Amadeus Proprietary and Confidential Information: unauthorized use and disclosure strictly forbidden. 2015 - Amadeus s.a.s - All Rights Reserved.  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:amasec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:awsl="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:int="http://wsdl.amadeus.com/HotelAvailability_v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://wsdl.amadeus.com/HotelAvailability_v2_v4" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.amadeus.com/HotelAvailability_v2_v4" name="nullLET_HotelAvailability_2.0_4.0">
  <wsdl:documentation>Versions: [interface: 2.0 ; technical: 4.0]</wsdl:documentation>
  <wsp:Policy wsu:Id="MessagingPolicy">
    <wsam:Addressing wsp:Optional="true">
      <wsp:Policy>
        <wsam:AnonymousResponses />
      </wsp:Policy>
    </wsam:Addressing>
  </wsp:Policy>
  <wsp:Policy wsu:Id="AmadeusPolicy">
    <wsp:PolicyReference URI="#MessagingPolicy" />
  </wsp:Policy>
  <wsdl:import namespace="http://wsdl.amadeus.com/HotelAvailability_v2" location="HotelAvailability_2.0.wsdl" />
  <wsdl:types>
    <xs:schema>
      <xs:import schemaLocation="AMA/2012B/AMA_WS_Session.xsd" namespace="http://xml.amadeus.com/2010/06/Session_v3" />
      <xs:import schemaLocation="AMA_WSLink.xsd" namespace="http://wsdl.amadeus.com/2010/06/ws/Link_v1" />
      <xs:import schemaLocation="AMA/2012B/AMA_SecurityHostedUser.xsd" namespace="http://xml.amadeus.com/2010/06/Security_v1" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Session_3.000">
    <wsdl:part name="session" element="awsse:Session" />
  </wsdl:message>
  <wsdl:message name="TransactionFlowLink_1.0">
    <wsdl:part name="link" element="awsl:TransactionFlowLink" />
  </wsdl:message>
  <wsdl:message name="AMA_SecurityHostedUser_1.000">
    <wsdl:part name="security" element="amasec:AMA_SecurityHostedUser" />
  </wsdl:message>
  <wsdl:binding name="HotelAvailability_Binding" type="int:HotelAvailability_PT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Hotel_EnhancedPricing">
      <soap:operation soapAction="http://webservices.amadeus.com/Hotel_EnhancedPricing_2.0" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Hotel_EnhancedSingleAvail">
      <soap:operation soapAction="http://webservices.amadeus.com/Hotel_EnhancedSingleAvail_2.0" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Hotel_MultiAvailability">
      <soap:operation soapAction="http://webservices.amadeus.com/Hotel_MultiAvailability_10.0" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Hotel_MultiSingleAvailability">
      <soap:operation soapAction="http://webservices.amadeus.com/Hotel_MultiSingleAvailability_10.0" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HotelAvailability_Service">
    <wsdl:port binding="tns:HotelAvailability_Binding" name="HotelAvailability_Port">
      <wsp:PolicyReference URI="#AmadeusPolicy" />
      <soap:address location="https://nodeD3.production.webservices.amadeus.com/1ASIWLUXLET" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
<!--1F8B08000000000000FF6D8EB10AC2401044FB7CC5968A1836A7A6B82EA844218260C07A8D2B2E5C2EE1B206F2F71E5AD8580E8F7933257B0EA4D279506979506A7B0B064DBEC4CDD264503F5F61B8D30499B198DBD51ACA53BD40B488C9F5B2ABA0FC1ABA002387218A623DC51493AD13F60AD4F74E9ACF8485E2176056EDEB79741467F0D4B28543A7EC8A91C4D14D9CE8941CBD727850F30FC6936F908AFC36BD000000-->
